import {
  ConnectButton,
  IfWalletConnected,
  WalletDropdown,
  WalletProfile,
  DisconnectButton,
  IfWalletNotConnected,
} from "@flair-sdk/react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Flair Wallet Integration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://flair.dev">Flair</a> examples!
        </h1>

        <p className={styles.description}>
          This example shows how to integrate Flair wallet component in a
          Next.js app and customize the styling.
        </p>

        <div className={styles.grid}>
          {/* Render a simple connect button */}
          <IfWalletNotConnected>
            Your custom styled button: 
            <ConnectButton className="my-custom-connect-button-class" />
          </IfWalletNotConnected>

          {/* If user is connected render a dropdown */}
          <IfWalletConnected>
            <WalletDropdown />
          </IfWalletConnected>

          {/* Render a wallet profile right after connect button (to avoid using IfWallet... components) */}
          {/* <ConnectButton>
            <WalletProfile />
          </ConnectButton> */}

          {/* Render a dropdown with wallet profile and menu right after connect button */}
          {/* <ConnectButton>
            <WalletDropdown />
          </ConnectButton> */}

          {/* Render a disconnect button after user has connected */}
          {/* <ConnectButton>
            <DisconnectButton />
          </ConnectButton> */}
        </div>
      </main>
    </div>
  );
};

export default Home;
